services:
  user-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: user-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Example123!"
    ports:
      - "1434:1433"
